version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build:
      context: ./backend
      dockerfile: Dockerfile.postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
