version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres
    build:
      context: ./backend
      dockerfile: Dockerfile.postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx/nginx.conf.d:/etc/nginx/nginx.conf.d
    depends_on:
      - backend
